#define DATASET_SIZE_EMPTY 0
#define DATASET_SIZE_TRIVIAL 1
#define DATASET_SIZE_SMALL 100
#define DATASET_SIZE_MODERATE 1000
#define DATASET_SIZE_LARGE 10000
#define DATASET_SIZE_HUGE 100000

#define RANDOM_VECTOR 1
#define SORTED_VECTOR 2
